name: "Get & Cache Dependencies"
description: "Get dependencies (via npm) and cache them for future runs"
inputs:
  caching: 
    description: "Wether Cache dependencies or not"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true' || inputs.caching == 'false'
        run: npm ci
        shell: bash